name: 打包React项目
on: push
jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest
    steps:
      - name: 拉取项目
        uses: actions/checkout@v6
      - run: pwd
      - run: npm --version
      - name: 安装依赖
        run: npm install
      - name: 打包项目
        run: npm run build