on: push

jobs:
    action1:
        runs-on: ubuntu-latest
        steps:
        - run: pwd
        - run: ls
    action2:
        runs-on: windows-latest
        steps:
        - run: node --version
